# -------------------------------------------------------------------
# use nocorrect alias to prevent auto correct from "fixing" these
# -------------------------------------------------------------------
alias 1='cd +1'
alias 2='cd +2'
alias 3='cd +3'
alias 4='cd +4'
alias 5='cd +5'
alias 6='cd +6'
alias 7='cd +7'
alias 8='cd +8'
alias 9='cd +9'
alias _=sudo
alias ack='nocorrect ack'
alias allgroups='cut -d: -f1 /etc/group | sort'
alias b='${(z)BROWSER}'
alias bower='noglob bower'
alias cd='nocorrect cd'
alias cdf='cd "$(pfd)"'
alias cp='nocorrect cp -i'
alias d='dirs -v'
alias df='df -kh'

# -------------------------------------------------------------------
# Docker
# -------------------------------------------------------------------
alias dockkilla='docker kill $(docker ps -q)'
alias dockrm='docker rm $(docker ps -a -q)'
alias dockrmi='docker rmi $(docker images -q)'
alias dockspec=inspectcontainer
alias du='du -kh'
alias e='${(z)VISUAL:-${(z)EDITOR}}'
alias ebuild='nocorrect ebuild'
alias et='vim ~/.tmux.conf'
alias ev='vim ~/.vimrc'
alias ez='vim ~/.zshrc'
alias fc='noglob fc'
alias find='noglob find'
alias ftp='noglob ftp'

# -------------------------------------------------------------------
# Git
# -------------------------------------------------------------------
alias g=git
alias gCO='gCo $(gCl)'
alias gCT='gCt $(gCl)'
alias gCa='git add $(gCl)'
alias gCe='git mergetool $(gCl)'
alias gCl='git status | sed -n "s/^.*both [a-z]*ed: *//p"'
alias gCo='git checkout --ours --'
alias gCt='git checkout --theirs --'
alias gR='git remote'
alias gRa='git remote add'
alias gRb=git-hub-browse
alias gRl='git remote --verbose'
alias gRm='git remote rename'
alias gRp='git remote prune'
alias gRs='git remote show'
alias gRu='git remote update'
alias gRx='git remote rm'
alias gS='git submodule'
alias gSI='git submodule update --init --recursive'
alias gSa='git submodule add'
alias gSf='git submodule foreach'
alias gSi='git submodule init'
alias gSl='git submodule status'
alias gSm=git-submodule-move
alias gSs='git submodule sync'
alias gSu='git submodule foreach git pull origin master'
alias gSx=git-submodule-remove
alias gb='git branch'
alias gbL='git branch -av'
alias gbM='git branch -M'
alias gbS='git show-branch -a'
alias gbX='git branch -D'
alias gbc='git checkout -b'
alias gbl='git branch -v'
alias gbm='git branch -m'
alias gbs='git show-branch'
alias gbx='git branch -d'
alias gc='git commit --verbose'
alias gcF='git commit --verbose --amend'
alias gcO='git checkout --patch'
alias gcP='git cherry-pick --no-commit'
alias gcR='git reset "HEAD^"'
alias gca='git commit --verbose --all'
alias gcc='nocorrect gcc'
alias gcf='git commit --amend --reuse-message HEAD'
alias gcl=git-commit-lost
alias gcm='git commit --message'
alias gco='git checkout'
alias gcp='git cherry-pick --ff'
alias gcr='git revert'
alias gcs='git show'
alias gd='git ls-files'
alias gdc='git ls-files --cached'
alias gdi='git status --porcelain --short --ignored | sed -n "s/^!! //p"'
alias gdk='git ls-files --killed'
alias gdm='git ls-files --modified'
alias gdu='git ls-files --other --exclude-standard'
alias gdx='git ls-files --deleted'
alias get='curl --continue-at - --location --progress-bar --remote-name --remote-time'
alias gf='git fetch'
alias gfc='git clone'
alias gflog='git reflog | grep -A1 pull | head -2'
alias gfm='git pull'
alias gfr='git pull --rebase'
alias gg='git grep'
alias ggL='git grep --files-without-matches'
alias ggi='git grep --ignore-case'
alias ggl='git grep --files-with-matches'
alias ggv='git grep --invert-match'
alias ggw='git grep --word-regexp'
alias ghc='stack exec -- ghc'
alias ghci='stack exec -- ghci'
alias giA='git add --patch'
alias giD='git diff --no-ext-diff --cached --word-diff'
alias giR='git reset --patch'
alias giX='git rm -rf --cached'
alias gia='git add'
alias gid='git diff --no-ext-diff --cached'
alias gir='git reset'
alias gist='nocorrect gist'
alias giu='git add --update'
alias gix='git rm -r --cached'
alias gl='git log --topo-order --pretty=format:"${_git_log_medium_format}"'
alias glb='git log --topo-order --pretty=format:"${_git_log_brief_format}"'
alias glc='git shortlog --summary --numbered'
alias gld='git log --topo-order --stat --patch --full-diff --pretty=format:"${_git_log_medium_format}"'
alias glg='git log --topo-order --all --graph --pretty=format:"${_git_log_oneline_format}"'
alias glo='git log --topo-order --pretty=format:"${_git_log_oneline_format}"'
alias globurl='noglob urlglobber '
alias gls='git log --topo-order --stat --pretty=format:"${_git_log_medium_format}"'
alias gm='git merge'
alias gmC='git merge --no-commit'
alias gmF='git merge --no-ff'
alias gma='git merge --abort'
alias gmt='git mergetool'
alias gp='git push'
alias gpA='git push --all && git push --tags'
alias gpa='git push --all'
alias gpc='git push --set-upstream origin "$(git-branch-current 2> /dev/null)"'
alias gpf='git push --force'
alias gpp='git pull origin "$(git-branch-current 2> /dev/null)" && git push origin "$(git-branch-current 2> /dev/null)"'
alias gpt='git push --tags'
alias gr='git rebase'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias grep='nocorrect grep --color=auto'
alias gri='git rebase --interactive'
alias grs='git rebase --skip'
alias gs='git stash'
alias gsL=git-stash-dropped
alias gsS='git stash save --patch --no-keep-index'
alias gsX=git-stash-clear-interactive
alias gsa='git stash apply'
alias gsd='git stash show --patch --stat'
alias gsl='git stash list'
alias gsp='git stash pop'
alias gsr=git-stash-recover
alias gss='git stash save --include-untracked'
alias gsw='git stash save --include-untracked --keep-index'
alias gsx='git stash drop'
alias gwC='git clean -f'
alias gwD='git diff --no-ext-diff --word-diff'
alias gwR='git reset --hard'
alias gwS='git status --ignore-submodules=${_git_status_ignore_submodules}'
alias gwX='git rm -rf'
alias gwc='git clean -n'
alias gwd='git diff --no-ext-diff'
alias gwr='git reset --soft'
alias gws='git status --ignore-submodules=${_git_status_ignore_submodules} --short'
alias gwx='git rm -r'

alias heroku='nocorrect heroku'
alias history='noglob history'
alias history-stat='history 0 | awk ''{print $2}'' | sort | uniq -c | sort -n -r | head'
alias http-serve='python -m SimpleHTTPServer'
alias l='ls -1A'
alias la='ll -A'
alias lc='lt -c'
alias lk='ll -Sr'
alias ll='ls -lh'
alias lm='la | "$PAGER"'
alias ln='nocorrect ln -i'
alias locate='noglob locate'
alias lr='ll -R'
alias ls='ls -G'
alias lt='ll -tr'
alias lu='lt -u'
alias lx='ll -XB'
alias man='nocorrect man'
alias mkdir='nocorrect mkdir -p'
alias mv='nocorrect mv -i'
alias mysql='nocorrect mysql'
alias o=open
alias p='${(z)PAGER}'
alias pbc=pbcopy
alias pbp=pbpaste
alias po=popd
alias pu=pushd
alias pushdf='pushd "$(pfd)"'
alias rake='noglob rake'
alias rm='nocorrect rm -i'
alias rsync='noglob rsync'
alias run-help=man
alias scp='noglob scp'
alias sftp='noglob sftp'
alias sl=ls

# -------------------------------------------------------------------
# Tmux
# -------------------------------------------------------------------
alias ta='tmux attach -t'
alias tkill='tmux kill-session -t'
alias tls='tmux ls'
alias tmux='tmux -2'
alias tnew='tmux new -s'
alias topc='top -o cpu'
alias topm='top -o vsize'
alias type='type -a'
alias which-command=whence
